### ISSUE TITLE
Fail to save activity to file

### ISSUE THREAD

**Issue by radiotaiso** [ucoria-itexico/nonova#19]
```
Want to save activity to file? [y/N]y
Traceback (most recent call last):
  File "nonova.py", line 149, in <module>
    sys.exit(main())
  File "nonova.py", line 140, in main
    new_activity()
  File "nonova.py", line 64, in new_activity
    save_activity(a)
  File "nonova.py", line 88, in save_activity
    novaconf.set("Activities", "{} {}".format(act.id, i), getattr(act, i))
  File "/Library/Python/2.7/site-packages/backports/configparser/__init__.py", line 1238, in set
    _, option, value = self._validate_value_types(option=option, value=value)
  File "/Library/Python/2.7/site-packages/backports/configparser/__init__.py", line 1221, in _validate_value_types
    raise TypeError("option values must be strings")
TypeError: option values must be strings
```

My .ini file

```
cat viernes.ini                                                                                                         10.9s  Fri Mar 24 15:46:38 2017
[Credentials]
user = ucoria@itexico.com
pass = ****
os = darwin

[Activities]
```

**Comment by GurgehMorat** [comment]
Pushed commit and doing an MR

**Comment by radiotaiso** [comment]
ticket was constructed but never assigned a value to it so it was always null.

DUH!

https://github.com/ucoria-itexico/nonova/commit/e6ec2c686feb7d1faf7d99de81a6cc8da58ddb25
