### ISSUE TITLE
When file already exists, script crashes.

### ISSUE THREAD

**Issue by radiotaiso** [ucoria-itexico/nonova#4]
``` 
> python .\nonova.py -c config.ini
Traceback (most recent call last):
  File ".\nonova.py", line 79, in <module>
    sys.exit(main())
  File ".\nonova.py", line 76, in main
    config(args)
  File ".\nonova.py", line 57, in config
    confparse.read(confparse.nonovaconfigfile)
  File "C:\Python27\lib\site-packages\backports\configparser\__init__.py", line 705, in read
    self._read(fp, filename)
  File "C:\Python27\lib\site-packages\backports\configparser\__init__.py", line 1039, in _read
    (p, -1) for p in self._inline_comment_prefixes)
AttributeError: 'NoNovaConfigParser' object has no attribute '_inline_comment_prefixes'
```

**Comment by radiotaiso** [comment]
Fixed in https://github.com/ucoria-itexico/nonova/commit/d60e724f4c4eed3e8806e7173704c39a0ae21cc9

Script was trying to do things outside the instanced object, fear no more, a new function was created where the code to verify if you already have a configfile can live happy.
